from torchrec.model.seq.caser import Caser
from torchrec.model.seq.din import DIN
from torchrec.model.seq.fpmc import FPMC
from torchrec.model.seq.gru4rec import GRU4Rec
from torchrec.model.seq.hgn import HGN
from torchrec.model.seq.narm import NARM
from torchrec.model.seq.npe import NPE
from torchrec.model.seq.sasrec import SASRec
from torchrec.model.seq.stamp import STAMP
from torchrec.model.seq.transrec import TransRec