from .bpr import BPR
from .cml import CML
from .ease import EASE
from .irgan import IRGAN
from .itemknn import ItemKNN
from .logisticmf import LogisticMF
from .ncf import NCF
from .slim import SLIM
from .wrmf import WRMF
from .dssm import DSSM