from recstudio.model.mf.bpr import BPR
from recstudio.model.mf.cml import CML
from recstudio.model.mf.ease import EASE
from recstudio.model.mf.irgan import IRGAN
from recstudio.model.mf.itemknn import ItemKNN
from recstudio.model.mf.logisticmf import LogisticMF
from recstudio.model.mf.ncf import NCF
from recstudio.model.mf.slim import SLIM
from recstudio.model.mf.wrmf import WRMF