from torchrec.model.mf.bpr import BPR
from torchrec.model.mf.cml import CML
from torchrec.model.mf.ease import EASE
from torchrec.model.mf.irgan import IRGAN
from torchrec.model.mf.itemknn import ItemKNN
from torchrec.model.mf.logisticmf import LogisticMF
from torchrec.model.mf.ncf import NCF
from torchrec.model.mf.slim import SLIM
from torchrec.model.mf.wrmf import WRMF
