# for training all models
learning_rate: 0.001
weight_decay: 0
learner: adam
scheduler: ~
epochs: 100
batch_size: 2048
num_workers: 0 # please do not use this parameter, slowing down the training process
gpu: ~

# used for training tower-based model
ann: {index: 'IVFx,Flat', parameter: ~}  ## 1 HNSWx,Flat; 2 Flat; 3 IVFx,Flat ## {nprobe: 1}  {efSearch: 1}
sampler: ~
negative_count: 1
embed_dim: 64

# used for evaluating tower-based model
eval_batch_size: 20
split_ratio: [0.8,0.1,0.1]
test_metrics: [recall, precision, map, ndcg, mrr, hit]
val_metrics: [recall, ndcg]
topk: 100
cutoff: 10
early_stop_mode: max
